[[constraint]]
  name = "github.com/kr/pty"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/nfnt/resize"

[[constraint]]
  branch = "master"
  name = "golang.org/x/image"
